### ISSUE TITLE
Why did u use Jquery

### ISSUE THREAD

**Issue by shahidweb** [leo6104/ngx-slick-carousel#60]
how to use without jquery files pls help

**Comment by Sampath-Lokuge** [comment]
Yes, Jquery is an antipattern for Angular apps. Will we have this Module without Jquery?

**Comment by leo6104** [comment]
It use `slick-carousel` and `slick-carousel` use jQuery. If slick-carousel has new update that remove jQuery library dependencies, we can remove jquery dependencies.

But i think they stop next development process because it already have lots of alternative carousel library in Vanilla JS.

My recommendation is `swiper.js`. I use swiper.js in my own angular projects and it doesn't require jQuery dependencies.
